name: CI

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  test:
    name: Test Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      fail-fast: true
      matrix:
        node:
          - 18
          - 20
          - 22
          - 24

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node-version: ${{ matrix.node }}

      - name: Build
        run: npm run build

      - name: Run test
        run: npm run test

  code-checks:
    name: Code checks
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run format
        run: npm run format

      - name: Run lint
        run: npm run lint

      - name: Run docs:build
        run: npm run docs:build

  ci-ok:
    name: CI OK
    runs-on: ubuntu-latest
    if: always()
    needs:
      - test
      - code-checks
    steps:
      - name: Exit with error if some jobs are not successful
        run: exit 1
        if: ${{ always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')) }}
